# Generated by Django 5.2.8 on 2026-01-14 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profissionais', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prescricao',
            name='consulta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.consulta'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_profissional', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescricao',
            name='profissonal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profissionais.profissional'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='profissonal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profissionais.profissional'),
        ),
    ]
