# Generated by Django 5.2.8 on 2025-12-20 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profissionais', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescricao',
            name='consulta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.consulta'),
        ),
        migrations.AddField(
            model_name='prescricao',
            name='profissonal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profissionais.profissional'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='profissonal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profissionais.profissional'),
        ),
    ]
