# Generated by Django 5.2.8 on 2025-12-20 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profissionais', '0002_initial'),
        ('telemedicina', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prontuario',
            name='consulta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prontuario', to='usuarios.consulta'),
        ),
        migrations.AddField(
            model_name='teleconsulta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teleconsultas', to='usuarios.paciente'),
        ),
        migrations.AddField(
            model_name='teleconsulta',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teleconsultas', to='profissionais.profissional'),
        ),
    ]
