# Generated by Django 5.2.8 on 2025-12-20 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internacao',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internacoes', to='usuarios.paciente'),
        ),
        migrations.AddField(
            model_name='internacao',
            name='leito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.leito'),
        ),
        migrations.AddField(
            model_name='leito',
            name='unidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leitos', to='hospital.unidadesaude'),
        ),
    ]
