# Generated by Django 5.2.8 on 2026-01-14 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atendimento', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('presencial', 'Presencial'), ('tele', 'Telemedicina')], default='presencial', max_length=20)),
                ('queixa_principal', models.TextField()),
                ('diagnostico', models.TextField()),
                ('prescricao', models.TextField()),
                ('evolucao_clinica', models.TextField()),
                ('hash_seguranca', models.CharField(editable=False, max_length=64, null=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='usuarios.paciente')),
            ],
        ),
    ]
